In [1]:
import pandas as pd

df_resultados = pd.read_csv("RESULTADOS_2024.csv", sep=";", encoding="latin1", low_memory=False)

In [2]:
df_resultados = df_resultados.drop(columns=['NU_SEQUENCIAL', 'NU_ANO', 'CO_MUNICIPIO_ESC', 'CO_UF_ESC', 'CO_MUNICIPIO_PROVA', 'CO_UF_PROVA',
                                            'SG_UF_ESC',	'TP_DEPENDENCIA_ADM_ESC',	'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'TP_PRESENCA_CN',
                                            'TP_PRESENCA_CH',	'TP_PRESENCA_LC','TP_PRESENCA_MT',	'CO_PROVA_CN',	'CO_PROVA_CH',	'CO_PROVA_LC',
                                            'CO_PROVA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT',
                                            'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
                                            'TP_STATUS_REDACAO',	'NU_NOTA_COMP1',	'NU_NOTA_COMP2',	'NU_NOTA_COMP3',	'NU_NOTA_COMP4',	'NU_NOTA_COMP5'])

df_resultados = df_resultados.rename(columns={
    "CO_ESCOLA": "codigo_escola",
    "NO_MUNICIPIO_ESC": "municipio_escola",
    "NO_MUNICIPIO_PROVA": "municipio_prova",
    "SG_UF_PROVA": "uf_prova",
    "NU_NOTA_CN": "nota_ciencias_natureza",
    "NU_NOTA_CH": "nota_ciencias_humanas",
    "NU_NOTA_LC": "nota_linguagens_codigos",
    "NU_NOTA_MT": "nota_matematica",
    "NU_NOTA_REDACAO": "nota_redacao"
})

df_resultados.head(5)

,codigo_escola,municipio_escola,municipio_prova,uf_prova,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao
0,23052929.0,Aratuba,Aratuba,CE,436.8,377.8,423.4,427.1,300.0
1,42103770.0,Tijucas,Tijucas,SC,521.9,601.9,605.5,689.2,920.0
2,NaN,NaN,Rolândia,PR,363.0,548.4,557.2,456.4,480.0
3,NaN,NaN,Osasco,SP,550.7,553.8,605.9,629.1,740.0
4,21150354.0,Alto Alegre do Maranhão,São Mateus do Maranhão,MA,NaN,NaN,NaN,NaN,NaN

In [21]:
def notas_por_escola(escolas):
    # Converte 'codigo_escola' para coluna numérica
    df_resultados['codigo_escola'] = pd.to_numeric(df_resultados['codigo_escola'], errors='coerce')
    for codigo, nome in escolas:
        df_escola = df_resultados[df_resultados['codigo_escola'] == codigo]
        df_escola = df_escola.drop(columns=['codigo_escola'])
        df_escola.to_csv(f"notas_{nome}.csv", index=False, sep=";", encoding="latin1")

In [22]:
anglo_liceu = (35107414, "anglo_liceu")
etapa = (35286187, "etapa")
otoniel_mota = (35024119, "otoniel_mota")
santa_ursula = (35114960, "santa_ursula")
sao_sabas = (35140004, "sao_sabas")

escolas = [anglo_liceu, etapa, otoniel_mota, santa_ursula, sao_sabas]

In [23]:
notas_por_escola(escolas)